## Docs: https://learn.microsoft.com/en-us/windows/wsl/wsl-config#wslconf
# Configure local settings with wsl.conf per-distribution for each Linux
# distribution running on WSL 1 or WSL 2.

# systemd support [1]. Additional boot options are available in Windows 11 and
# later [2].
#
# refs:
# - [1]: https://learn.microsoft.com/en-us/windows/wsl/wsl-config#systemd-support
# - [2]: https://learn.microsoft.com/en-us/windows/wsl/wsl-config#boot-settings
[boot]
systemd = true

[automount]
# By default, WSL mounts fixed drives (e.g., C: and D:) under `/mnt`, however,
# reportedly it also mounts and locks removable drives [1], thus, it's disabled.
#
# refs:
# - [1]: https://github.com/microsoft/WSL/issues/7972
enabled = false
# Ensure `/etc/fstab` (File system table) is parsed and applied when WSL starts,
# which allows for custom mounts while automount is disabled.
#
# /etc/fstab example:
# ```
# # Mount the C: drive to /mnt/c with specific options [1]
# C: /mnt/c drvfs metadata,uid=1000,gid=1000,umask=022,fmask=011 0 0
# ```
#
# refs:
# - [1]: https://learn.microsoft.com/en-us/windows/wsl/wsl-config#automount-options
mountFsTab = true

# Interop settings control how WSL interacts with Windows applications and the
# Windows environment. Options are available in Windows Build 17713 and later.
[interop]
# Enabling interop allows WSL to run Windows executables directly from Linux.
enabled = true
# By default, WSL appends Windows PATH to the Linux PATH for discoverability of
# Windows executables. Setting this to false prevents that while it's still possible
# to run Windows executables by specifying their full path.
appendWindowsPath = false
