# shellcheck disable=SC2148
# /etc/skel/.bashrc
# This bashrc file is created by Chawye Hsu, licensed under the MIT license.
#------------------------------------------------------------------------------#
# Support Platforms:
#    Windows: Git-Bash/MSYS2
#      macOS: Bash, Zsh
#      Linux: Bash
#------------------------------------------------------------------------------#
# Test for an interactive shell.
[[ $- != *i* ]] && return

# Switch to pwsh if it's available and enabled
_pwshmark="$HOME/.cache/powershell/loginsh.mark"
_pwshbin="$HOME/.pixi/bin/pwsh"
# shellcheck disable=SC2086
[ -f $_pwshmark ] && [ -x $_pwshbin ] && export SHELL=$_pwshbin && exec $_pwshbin -l

shtype="bash"
# zsh autoload issue: https://github.com/astral-sh/uv/issues/10707
[ -n "$ZSH_VERSION" ] && shtype="zsh" && autoload -Uz compinit && compinit
#-----------------------#
# Environment Variables #
#-----------------------#
# Xterm colors
[ "$TERM" = "xterm" ] && export TERM=xterm-256color
export LANG=en_US.UTF-8
export TZ=UTC-8
export PYTHONUTF8=1
# default editor
export EDITOR=nano
# Always display git dirty state
export GIT_PS1_SHOWDIRTYSTATE=1
# Enable Node.js (chalk) color
export FORCE_COLOR=1
# XDG environment variables
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
# XDG compliance
export INPUTRC="$XDG_CONFIG_HOME/readline/inputrc"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
if [ ! -f "$XDG_CACHE_HOME/.nodomestic" ]; then
  export HOMEBREW_BREW_GIT_REMOTE="https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git"
  # Rustup
  export RUSTUP_DIST_SERVER="https://mirrors.ustc.edu.cn/rust-static"
  export RUSTUP_UPDATE_ROOT="https://mirrors.ustc.edu.cn/rust-static/rustup"
fi
# PATH updates -
case "$OSTYPE" in
  darwin*)
    # NOTES: macOS's default PATH (definition in `/etc/paths`):
    #   "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    #
    # A `/Library/Apple/usr/bin` path will be added when the
    # Xcode command line tools is installed.

    # PATH updates - Add super bin directory installed by Homebrew:
    if [[ -d "/usr/local/sbin" && ":$PATH:" != *":/usr/local/sbin:"* ]]; then
      export PATH="/usr/local/sbin:$PATH"
    fi

    # PATH updates - Add Homebrew:
    _homebrew="/opt/homebrew/bin/brew"
    [[ -f $_homebrew ]] && eval "$($_homebrew shellenv)"

    # git-prompt (Homebrew):
    _gitprompt="$(brew --prefix git)/etc/bash_completion.d/git-prompt.sh"
    # shellcheck disable=SC1090
    [ -f "$_gitprompt" ] && source "$_gitprompt"

    # bash-completion:
    _bashcomp="/usr/local/etc/bash_completion"
    # shellcheck disable=SC1090
    [ -f "$_bashcomp" ] && source "$_bashcomp"
    ;;
  linux*)
    # PATH updates - Add linuxbrew:
    _linuxbrew1="/home/linuxbrew/.linuxbrew/bin/brew" # sudo
    [[ -f $_linuxbrew1 ]] && eval "$($_linuxbrew1 shellenv)"
    _linuxbrew2="$HOME/.linuxbrew/bin/brew" # non sudo
    [[ -f $_linuxbrew2 ]] && eval "$($_linuxbrew2 shellenv)"

    # Bun javascript runtime:
    _bunexe="$HOME/.bun/bin/bun"
    [ -f "$_bunexe" ] && export BUN_INSTALL="$HOME/.bun" && export PATH="$BUN_INSTALL/bin:$PATH"

    # Add git-prompt (system):
    _gitprompts=(
      "/usr/share/git/completion/git-prompt.sh"
      "/usr/share/git-core/contrib/completion/git-prompt.sh"
      "/usr/share/doc/git/contrib/completion/git-prompt.sh"
    )
    for _gitprompt in "${_gitprompts[@]}"; do
      # shellcheck disable=SC1090
      [ -f "$_gitprompt" ] && source "$_gitprompt" && break
    done
esac
# PATH updates - Add `~/.local/bin`:
_localbin="$HOME/.local/bin"
if [[ -d "$_localbin" && ":$PATH:" != *":$_localbin:"* ]]; then
  export PATH="$_localbin:$PATH"
fi

#------------------#
#  keybind compat  #
#------------------#
if [ -x "$(command -v stty)" ]; then
  # unbind Ctrl-z for SIGTSTP
  # https://superuser.com/questions/476704/
  # https://unix.stackexchange.com/questions/314284/
  # https://superuser.com/questions/1031835/
  stty susp undef
fi

#--------------------#
#  ls and dircolors  #
#--------------------#
# LS_COLORS generated by [vivid](https://github.com/sharkdp/vivid)
if [ -x "$(command -v vivid)" ]; then
  # shellcheck disable=SC2155
  export LS_COLORS="$(vivid -m 8-bit generate snazzy)"
fi
# Uniform `ls` command on all platforms
case "$OSTYPE" in
  darwin*)
    if [ -x "$(command -v gls)" ]; then
      alias ls='gls -F --group-directories-first --color' # GNU ls
    else
      alias ls="ls -F -G" # BSD/macOS ls
    fi
    ;;
  linux*|cygwin*|msys*)
    # Too many unconcerned files and directories in Windows $HOME, ignore them.
    ignoreList=("_viminfo" "navdb.csv" "NTUSER*" "ntuser*" "Local Settings*" \
      "Application Data*" "My Documents*" "NetHood*" "PrintHood*" "Recent*" \
      "SendTo*" "Templates*" "Cookies*" "3D Objects" "Thumbs.db" "Start Menu" \
      "desktop.ini" "Saved Games" "Creative Cloud Files")
    for item in "${ignoreList[@]}"; do
      lsIgnore+="'$item',"
    done

    # shellcheck disable=SC2139
    alias ls="ls -F --group-directories-first --color --ignore={$lsIgnore}"
    ;;
esac
alias l="ls"
alias la="ls -A"
alias ll="ls -lh"
alias lla="ls -lhA"

#---------------#
# Unify Aliases #
#---------------#
alias c="clear"
alias :q="exit"
alias ..="cd .."
alias ...="cd ../.."
alias myip="curl -s https://api.ip.sb/ip"
alias cls="clear"
case "$OSTYPE" in
  darwin*)
    alias here="open ."
    ;;
  cygwin*|msys*)
    if [ -x "$(command -v winpty)" ]; then
      # winpty fixes
      alias ipconfig="winpty ipconfig"
      alias nslookup="winpty nslookup"
      alias ping="winpty ping"
    fi
    # Emulate ifconfig on Windows MSYS
    alias ifconfig="ipconfig"
    alias open="explorer"
    alias here="open ."
    ;;
esac

#-------------------------------------#
#  ssh-agent on Git-Bash/MSYS2/MinGW  #
#-------------------------------------#
# ref: https://help.github.com/articles/working-with-ssh-key-passphrases/
if [ "$OSTYPE" = "msys" ] && [ -x "$(command -v ssh)" ]; then
  # ensure .ssh directory exists
  [ ! -d "$HOME/.ssh" ] && mkdir -p "$HOME/.ssh" >| /dev/null
  # test ssh is Win32-OpenSSH or not
  if [[ ! "$(ssh -V 2>&1)" == *"Windows"* ]]; then
    # we use $USERPROFILE instead of $HOME to locate SSH ENV,
    # so we can share ssh env between Git-Bash and MSYS2,
    # but be aware of that Win32-OpenSSH does not use SSH ENV
    agentenv="$HOME/.ssh/agent.env"
    # load ssh env
    # shellcheck disable=SC1090
    [ -f "$agentenv" ] && source "$agentenv" >| /dev/null
    # agentstatus:
    #   0=agent running w/ key;
    #   1=agent w/o key;
    #   2=agent not running.
    agentstatus=$(ssh-add -l >| /dev/null 2>&1; echo $?)
    if [ ! "$SSH_AUTH_SOCK" ] || [ "$agentstatus" -eq 2 ]; then
      # shellcheck disable=SC1090
      (umask 077; ssh-agent >| "$agentenv") && source "$agentenv" >| /dev/null
      ssh-add
    elif [ "$SSH_AUTH_SOCK" ] && [ "$agentstatus" -eq 1 ]; then
      ssh-add
    fi
    unset agentenv
  else
    ssh-agent >| /dev/null
    ssh-add
  fi
fi

#----------------------------------#
# Cross-platform programs settings #
#----------------------------------#
# PATHs
# PATH updates - Add `~/.cargo/bin`:
_cargobin="$HOME/.cargo/bin"
if [[ -d "$_cargobin" && ":$PATH:" != *":$_cargobin:"* ]]; then
  export PATH="$_cargobin:$PATH"
fi
# PATH updates - Add pixi bin:
_pixibin="$HOME/.pixi/bin"
if [[ -d "$_pixibin" && ":$PATH:" != *":$_pixibin:"* ]]; then
  export PATH="$_pixibin:$PATH"
  [ -x "$(command -v pixi)" ] && eval "$(pixi completion -s $shtype)"
fi
# moonbit
_moonbitbin="$HOME/.moon/bin"
if [[ -d "$_moonbitbin" && ":$PATH:" != *":$_moonbitbin:"* ]]; then
  export PATH="$_moonbitbin:$PATH"
fi
# conda
[ -x "$(command -v conda)" ] && eval "$(conda "shell.$shtype" 'hook')"
# bat
if [ -x "$(command -v bat)" ]; then
  export BAT_CONFIG_PATH="$XDG_CONFIG_HOME/bat/config"
  alias cat="bat"
fi
# Ruby rbenv
[ -x "$(command -v rbenv)" ] && eval "$(rbenv init -)"

#----------------------------#
# The Chawye's styled prompt #
#----------------------------#
# Override global prompt command to set terminal title
PROMPT_COMMAND='echo -ne "\033]0;$0\a"'

function styled_prompt() {
  # Color table
  local   RESET=$'\033[0m'
  # shellcheck disable=SC2034
  local   BLACK=$'\033[0;30m'
  # shellcheck disable=SC2034
  local     RED=$'\033[0;31m'
  local   GREEN=$'\033[0;32m'
  local  YELLOW=$'\033[0;33m'
  # shellcheck disable=SC2034
  local    BLUE=$'\033[0;34m'
  local MAGENTA=$'\033[0;35m'
  local    CYAN=$'\033[0;36m'
  # shellcheck disable=SC2034
  local   WHITE=$'\033[0;37m'
  # Terminal title
  local TERMTITLE=$'\033]0;$0\a'

  # Special system environment detection: WSL, MSYS2/MinGW
  if [[ "$(uname -r)" == *"icrosoft"* ]]; then
    DIST="$MAGENTA(WSL)$RESET"
  elif [ -n "$MSYSTEM" ]; then
    DIST="$MAGENTA($MSYSTEM)$RESET"
  else
    DIST=""
  fi

  # git-prompt
  # __git_ps1 not update issue:
  #  https://askubuntu.com/questions/896445/#comment2153553_1163371
  [ -n "$(declare -fF '__git_ps1')" ] && GITPS1="\$(__git_ps1 ' (%s)')"

  # PS1 command substitution issue with newline:
  #  https://stackoverflow.com/questions/33220492/
  #  https://stackoverflow.com/questions/21517281/
  PS1="$TERMTITLE$GREEN\h$DIST $YELLOW\W$CYAN$GITPS1$RESET"$'\n\$ '

  # Zsh support
  if [ -n "$ZSH_VERSION" ]; then
    setopt PROMPT_SUBST
    # shellcheck disable=SC2034
    PROMPT="$TERMTITLE$GREEN%m$DIST $YELLOW%1~$CYAN$GITPS1$RESET"$'\n\$ '
  fi
}

# starship
if [ -x "$(command -v starship)" ]; then
  # `--print-full-init` is explicitly used to avoid 2-phase init
  # overhead, see: https://github.com/starship/starship/issues/2637
  # shellcheck disable=SC1090
  source <(starship init $shtype --print-full-init)
else
  styled_prompt
fi

# zoxide
[ -x "$(command -v zoxide)" ] && eval "$(zoxide init $shtype)" && alias cd='z'
