# Reference: https://pixi.sh/latest/advanced/global_configuration/
change-ps1 = false

[mirrors]
"https://conda.anaconda.org/" = [
    "https://mirrors.sustech.edu.cn/anaconda/cloud/",
    "https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/"
]

[repodata-config]
disable-jlap = true
disable-zstd = true

[pypi-config]
index-url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
